# Generated by Django 4.1.2 on 2022-10-27 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(default='', max_length=20)),
                ('by', models.CharField(default='', max_length=200)),
                ('time', models.IntegerField(default=None, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hackernewsapp.base')),
                ('parent', models.IntegerField(default=0)),
                ('text', models.CharField(default='', max_length=2000)),
            ],
            bases=('hackernewsapp.base',),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hackernewsapp.base')),
                ('text', models.CharField(default='', max_length=2000)),
                ('url', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=2000)),
            ],
            bases=('hackernewsapp.base',),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hackernewsapp.base')),
                ('parts', models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('descendants', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=2000)),
                ('text', models.CharField(default='', max_length=2000)),
            ],
            bases=('hackernewsapp.base',),
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hackernewsapp.base')),
                ('parent', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
            bases=('hackernewsapp.base',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hackernewsapp.base')),
                ('descendants', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=2000)),
                ('url', models.CharField(default='', max_length=200)),
            ],
            bases=('hackernewsapp.base',),
        ),
    ]
