# Generated by Django 4.1.2 on 2022-10-27 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernewsapp', '0002_alter_base_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='kids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
