# Generated by Django 4.1.2 on 2022-10-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernewsapp', '0005_alter_base_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='parts',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
